# We deliberately ignore github.com/docker/docker because shed is using an old,
# not on github edition of docker with manual changes. As such we do some
# manual depedancy management of it by copying it back in after `dep ensure`.
# github.com/Sirupsen/logrus is the old name for github.com/sirupsen/logrus
# (note the capital "S"). Old docker/docker depends on the old logrus which
# no longer exists on github. ... I know. Engineers on the Garden team refer to
# this as "Sirupsengate" (or "sirupsengate", you pick just don't change your
# mind later).
ignored = ["github.com/docker/docker*", "github.com/Sirupsen/logrus"]

# --- garden owned libraries ---
[[constraint]]
name = "code.cloudfoundry.org/garden"
branch = "master"

[[constraint]]
name = "code.cloudfoundry.org/grootfs"
branch = "master"

[[constraint]]
name = "code.cloudfoundry.org/guardian"
branch = "master"

[[constraint]]
name = "code.cloudfoundry.org/idmapper"
branch = "master"

# --- other libraries ---
[[constraint]]
name = "code.cloudfoundry.org/clock"
revision = "e9dc86bbf0e5bbe6bf7ff5a6f71e048959b61f71"

[[constraint]]
name = "code.cloudfoundry.org/commandrunner"
revision = "501fd662150bcea5a42a9b5c1c283209720788c3"

[[constraint]]
name = "code.cloudfoundry.org/lager"
revision = "62951a8009ab331bb21dc418074fa54e66eb9b6a"

[[constraint]]
name = "github.com/docker/distribution"
revision = "856638e299eddf01964fa918ac1552d8aa2e22b3"

[[constraint]]
name = "github.com/eapache/go-resiliency"
revision = "b86b1ec0dd4209a588dc1285cdd471e73525c0b3"

[[constraint]]
name = "github.com/opencontainers/runtime-spec"
revision = "02137cd4e50b37a01665e1731fcd4ac2d2178230"

[[constraint]]
name = "golang.org/x/net"
revision = "195180cfebf7362bd243a52477697895128c8777"

[[constraint]]
name = "golang.org/x/sys"
revision = "9ccfe848b9db8435a24c424abbc07a921adf1df5"
