// This file was generated by counterfeiter
package fake_id

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-shed/layercake"
)

type FakeID struct {
	GraphIDStub        func() string
	graphIDMutex       sync.RWMutex
	graphIDArgsForCall []struct{}
	graphIDReturns     struct {
		result1 string
	}
}

func (fake *FakeID) GraphID() string {
	fake.graphIDMutex.Lock()
	fake.graphIDArgsForCall = append(fake.graphIDArgsForCall, struct{}{})
	fake.graphIDMutex.Unlock()
	if fake.GraphIDStub != nil {
		return fake.GraphIDStub()
	} else {
		return fake.graphIDReturns.result1
	}
}

func (fake *FakeID) GraphIDCallCount() int {
	fake.graphIDMutex.RLock()
	defer fake.graphIDMutex.RUnlock()
	return len(fake.graphIDArgsForCall)
}

func (fake *FakeID) GraphIDReturns(result1 string) {
	fake.GraphIDStub = nil
	fake.graphIDReturns = struct {
		result1 string
	}{result1}
}

var _ layercake.ID = new(FakeID)
