// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/garden-shed/docker_drivers/aufs"
)

type FakeRetrier struct {
	RetryStub        func(cb func() error) error
	retryMutex       sync.RWMutex
	retryArgsForCall []struct {
		cb func() error
	}
	retryReturns struct {
		result1 error
	}
}

func (fake *FakeRetrier) Retry(cb func() error) error {
	fake.retryMutex.Lock()
	fake.retryArgsForCall = append(fake.retryArgsForCall, struct {
		cb func() error
	}{cb})
	fake.retryMutex.Unlock()
	if fake.RetryStub != nil {
		return fake.RetryStub(cb)
	} else {
		return fake.retryReturns.result1
	}
}

func (fake *FakeRetrier) RetryCallCount() int {
	fake.retryMutex.RLock()
	defer fake.retryMutex.RUnlock()
	return len(fake.retryArgsForCall)
}

func (fake *FakeRetrier) RetryArgsForCall(i int) func() error {
	fake.retryMutex.RLock()
	defer fake.retryMutex.RUnlock()
	return fake.retryArgsForCall[i].cb
}

func (fake *FakeRetrier) RetryReturns(result1 error) {
	fake.RetryStub = nil
	fake.retryReturns = struct {
		result1 error
	}{result1}
}

var _ aufs.Retrier = new(FakeRetrier)
